config/routes.rb
Screener::Application.routes.draw do
  devise_for :users
  root 'pages#landing'  

  resources :submissions, except: [:edit, :update, :show]

  scope 'expert' do
  	get '/' => 'expert#index', as: 'expert'
  	get '/search' => 'expert#search', as: 'search'
  	scope 'submissions' do
  		put '/:id' => 'expert#update', as: 'update_doctor_result'
  		get '/:id' => 'expert#show', as: 'expert_show'
  	end
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :submission
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :user
  has_many :answers
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true, uniqueness: true
  validates :age, presence: true, numericality: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many  :submissions

  def full_name
  	first_name + " " + last_name
  end

  def expert?

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :email) }
  	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :age, :first_name, :last_name) }
  	devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password, :age, :first_name, :last_name) }
  end
end

app/controllers/checkups_controller.rb
class CheckupsController < ApplicationController
	before_action :authenticate_user

	def show
	end

	def new
	end

	def create
	end

	def destroy
	end
	
end

app/controllers/expert_controller.rb
class ExpertController < ApplicationController
	http_basic_authenticate_with name: "expert", password: "expert"

	def index
		@submissions = Submission.includes(:user).all
	end

	def show
		@submission = Submission.where(id: params[:id]).first
		unless @submission
			flash[:error] = 'تست یافت نشد.'
			return redirect_to expert_path
		end
		@answers = @submission.answers
	end

	def destroy
	end

	def update
		submission = Submission.where(id: params[:id]).first
		unless submission
			flash[:error] = 'تست یافت نشد.'
		else
			result = (params[:result] == "true" ? true : false)
			submission.update_attributes! doctor_result: result
			flash[:success] = 'نظر شما با موفقیت ثبت شد.'
		end
		return redirect_to expert_path
	end

	def search
		@submissions = User.includes(:submissions).all.to_a.select { |u| u.full_name.include? params[:name]}.map { |u| u.submissions }.flatten
		render layout: false
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def landing
	end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController

	before_action :authenticate_user!

	def index
		@submissions = current_user.submissions
	end

	def new
	end

	def create
		submission = current_user.submissions.create!
		params["submission"].each do |q,choice_index|
			submission.answers.create! choice: choice_index
		end
		flash[:success] = 'داده با موفقیت ثبت شد. منتظر اعلام نتایج باشید.'
		return redirect_to submissions_path
	end

	def destroy
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def persian_number(str)
		str = str.to_s if str.class == Fixnum
		str ? str.unpack('U*').map{ |e| (0..9).to_a.include?(e-48) ? e + 1728 : e }.pack('U*') : ''
	end

	def persian_date(date)
		(date ? persian_number(JalaliDate.new(date).format("%A %d %b %Y - %H:%m")) : '').split('-')[0]
	end

	def flash_class(level)
		case level
		when :notice then "alert alert-info"
		when :success then "alert alert-success"
		when :error then "alert alert-error"
		when :alert then "alert alert-error"
		end
	end


end

app/helpers/checkups_helper.rb
module CheckupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/expert/_table.html.erb
<div class="management with-font text-center" id="new">
	لیست تست‌های ثبت شده.
</div>

<div class="container with-margin">
	<div class="row">
		<% if submissions.any? %>
		<div class="col-md-10 col-md-offset-1">
			<table class="table table-stripped">
				<thead>
					<tr>
						<th> توسط </th>
						<th> تاریخ ثبت </th>
						<th> نظر سیستم </th>
						<th> نظر پزشک </th>
						<th></th>
						<th></th>

					</tr>
				</thead>
				<tbody>
					<% submissions.each do |submission| %>
					<tr>
						<td> <%= submission.user.full_name %> </td>
						<td> <%= persian_date(submission.created_at) %> </td>
						<td>
							<% if submission.classifier_result%>
							<span class="label label-danger">احتمال زیاد مبتلا هست.</span>
							<% elsif submission.classifier_result == false %>
							<span class="label label-success">احتمال زیاد مبتلا نیست.</span>
							<% else %>
							<span class="label label-primary">تست نشده.</span>
							<% end %>
						</td>
						<td>
							<% if submission.doctor_result%>
							<span class="label label-danger">مبتلا هست.</span>
							<% elsif submission.doctor_result == false %>
							<span class="label label-success">مبتلا نیست.</span>
							<% else %>
							<span class="label label-primary">نظر داده نشده.</span>
							<% end %>
						</td>
						<td> <%= link_to 'مشاهده پاسخ‌ها', expert_show_path(submission) , class: 'btn btn-default' %> </td>
						<td> <%= link_to 'ثبت نظر', '#', class: 'btn btn-warning', data: {toggle: "modal", target: "#myModal"} %> </td>


						<!-- Modal -->
						<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
							<div class="modal-dialog">
								<div class="modal-content">
									<div class="modal-header">
										<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
									</div>
									<div class="modal-body">
										<p> تشخیص شما برای این متقاضی چیست؟ </p>
									</div>
									<div class="modal-footer">
										<%= link_to 'مبتلا نیست', update_doctor_result_path(submission, result: false), class: 'btn btn-success' , method: :put%>
										<%= link_to 'مبتلا هست', update_doctor_result_path(submission, result: true), class: 'btn btn-danger', method: :put %>
									</div>
								</div>
							</div>
						</div>
					</tr>
					<% end %>
				</tbody>
				<!-- Button trigger modal -->
			</table>			
		</div>
		<% else %>
		<% end %>
	</div>
</div>

app/views/expert/index.html.erb
<form class="form-horizontal" id="live-search-form" method="post" action="<%= search_path %>">
    <div class="form-group">
      <label for="inputType" class="col-md-3 control-label">جستجو بر اساس نام کاربر</label>
      <div class="col-md-3">
          <input type="text" class="form-control" name="name" id="big-search-box">
      </div>
    </div>
</form>

<div id="live-search-results">
	<%= render partial: 'table', locals: {submissions: @submissions } %>
</div>

<script type='text/javascript'>
	$("#big-search-box").bind("keyup", function() {
  $("#big-search-box").addClass("loading"); // show the spinner
  var form = $("#live-search-form"); // grab the form wrapping the search bar.

  var url = "/expert/search"; // live_search action.   
  var formData = form.serialize(); // grab the data in the form   
  $.get(url, formData, function(html) { // perform an AJAX get

    $("#big-search-box").removeClass("loading"); // hide the spinner

    $("#live-search-results").html(html); // replace the "results" div with the results

   handle_animation();

});

});
</script>

app/views/expert/search.html.erb
<%= render partial: 'table', locals: {submissions: @submissions} %>

app/views/expert/show.html.erb
<% QUESTIONS.each_with_index do |question,i| %>
	<div class="row">
		<div class="col-md-5">
		</div>
		<div class="col-md-3">
			<b><%= question %></b>
			<%= CHOICES.keys[@answers[i].choice] %>
			<br><br><br>
		</div>
		<div class="col-md-4">
 		</div>
	</div>
<% end %>
<br><br>
<center>
<%= link_to 'بازگشت', expert_path, class: 'btn btn-info' %>
</center>

app/views/layouts/_message.html.erb
  <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>">
              <%= value %>
        </div>
  <% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse" role="navigation">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">سامانه‌ی هوشمند بررسی آسیب اوتیسم</a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
				<% if current_user %>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%= current_user.full_name %> <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><a href="/profile">پروفایل</a></li>
						<li class="divider"></li>
						<li><%= link_to 'خروج', destroy_user_session_path, method: :delete %></li>
					</ul>
				</li>
				<li><%= link_to 'تست‌ها', submissions_path %> </li>
				<li><a href="/">خانه</a></li>
				<% else %>
					<li><a href="/users/sign_in">ورود</a></li>
				<% end %>
			</ul>
			<ul class="nav navbar-nav navbar-left">
				<li><a href="#">درباره‌ی ما</a></li>
				<li><a href="#">حریم خصوصی</a></li>
				<li><a href="/contact_us">تماس با ما</a></li>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Screener</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>

	<%= render partial: 'layouts/navbar' %>
	<%= render 'layouts/message' %>
	<%= yield %>

</body>
</html>

app/views/submissions/index.html.erb
<div class="management with-font text-center" id="new">
	لیست تست‌های ثبت شده‌ی شما.
</div>

<div class="container with-margin">
	<div class="row">
		<% if @submissions.any? %>
		<div class="col-md-10 col-md-offset-1">
			<table class="table table-stripped">
				<thead>
					<tr>
						<th> تاریخ ثبت </th>
						<th> نظر سیستم </th>
						<th> نظر پزشک </th>
					</tr>
				</thead>
				<tbody>
					<% @submissions.each do |submission| %>
					<tr>
						<td> <%= persian_date(submission.created_at) %> </td>
						<td>
							<% if submission.classifier_result%>
								احتمال زیاد مبتلا هست.
							<% elsif submission.classifier_result == false %>
								احتمال زیاد مبتلا نیست.
							<% else %>
								منتظر باشید.
							<% end %>
						</td>
						<td>
							<% if submission.classifier_result%>
								مبتلا هست.
							<% elsif submission.classifier_result == false %>
								مبتلا نیست.
							<% else %>
								منتظر باشید.
							<% end %>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
		<% else %>
		<% end %>
	</div>
	<div class="row with-font text-center with-margin">
			<%= link_to 'تست جدید', new_submission_path, class: "btn btn-success" %>
	</div>
</div>

app/views/submissions/new.html.erb
<%= simple_form_for :submission, url: submissions_path, html: {class: 'form-horizontal', role: 'form', onsubmit: "return validate_form();"} do |f| %>
<div class="contrainer exam">
	<script type="text/javascript">
		function validate_form()
		{
			var radioButtons = $('input[type="radio"]');
			for(i = 0; i < radioButtons.length-1; i += <%= 3 %>) {
				var check = false;
				for(j = 0; j < <%= CHOICES.size %>; j++) {
					if(radioButtons[i+j].checked == true)
					{
						check = true;
						break;
					}

				}
				if(check)
					continue;

				alert("سوال شماره‌ی "+(Math.ceil(i/<%=CHOICES.size %>)+1).toString()+"خالی است. پرش کنید.");
				return false;
			}
			return true;
		}
	</script>

	<div class="row">
		<div class="col-md-3"></div>
		<div class="col-md-4">
			<% QUESTIONS.each_with_index do |question,index| %>
			<p>
				<fieldset id="question<%=index%>">
					<legend><b><%= persian_number(index+1) %>. </b><%= question%></legend>
					<%= f.collection_radio_buttons(
						"#{index}" ,CHOICES.each_with_index.map { |(choice,value),i| [i,choice]}, :first, :last
						) do |b|
						b.label { b.radio_button + b.text}
					end
					%>
				</fieldset>
			</p>
			<br>
			<% end %>
			<%= f.submit 'ثبت', class: 'btn btn-success' %>
		</div>
		<div class="col-md-4"></div>
	</div>
</div>

<% end %>